services:
  postgres:
    image: postgres:latest
    container_name: notification-enrichment-service-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6432:5432"
    restart: unless-stopped
    networks:
      - order-processing-service-network

networks:
  order-processing-service-network:
    driver: bridge
